export const UserActions = {
    // Login (Async)
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    // Logout (Async)
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    // Register (Async)
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    // Update User (Async)
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    // Revalidate Token (Async)
    REVALIDATE_TOKEN_REQUEST: 'REVALIDATE_TOKEN_REQUEST',
    REVALIDATE_TOKEN_SUCCESS: 'REVALIDATE_TOKEN_SUCCESS',
    REVALIDATE_TOKEN_FAILURE: 'REVALIDATE_TOKEN_FAILURE',
    // Get Local User (Async)
    LOAD_LOCAL_USER: 'LOAD_LOCAL_USER',
    
}